// <auto-generated />
using MTG_Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTG_Application.Migrations.CardDb
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MTG_Application.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ColorIdentity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Colors")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Foil")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageUri")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ManaCost")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ManaValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NonFoil")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Prices")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Rarity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SetCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SetName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TypeLine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Uri")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
